spring:
  application:
    name: CONFIG-DEFAULT
  datasource:
    url: jdbc:mysql://localhost:3306/banking_application
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
